version: '3'
services:
  mysql-docker:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8081:8081"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-docker